package com.laozhang.mybatis.mapper;

import com.laozhang.mybatis.model.TestMybatis;
import com.laozhang.mybatis.model.TestMybatisExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TestMybatisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_mybatis
     *
     * @mbg.generated
     */
    long countByExample(TestMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_mybatis
     *
     * @mbg.generated
     */
    int deleteByExample(TestMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_mybatis
     *
     * @mbg.generated
     */
    int insert(TestMybatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_mybatis
     *
     * @mbg.generated
     */
    int insertSelective(TestMybatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_mybatis
     *
     * @mbg.generated
     */
    List<TestMybatis> selectByExample(TestMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_mybatis
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TestMybatis record, @Param("example") TestMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_mybatis
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TestMybatis record, @Param("example") TestMybatisExample example);
}